### ISSUE TITLE
Character Show Page

### ISSUE THREAD

**Issue by mikedao** [mikedao/cobalt_reserve#18]
As a visitor, when I visit `/characters`
And I click on the name of one of the characters,
I am brought to its show page `/characters/:id`
and I can see all of its attributes

**Comment by rolentle** [comment]
@mikedao for this task do we want all of the columns on the characters' table?

**Comment by mikedao** [comment]
@rolentle I would say at this point, use your own discretion. I think it's a relatively trivial thing to add or remove later.
