### ISSUE TITLE
Add password confirmation for user registration

### ISSUE THREAD

**Issue by rolentle** [mikedao/cobalt_reserve#32]
As a user,
When I create an account
And I type in my password
And I type in the same password as password confirmation
Then I create a user

As a user
When I create an account
And I type in my password
And I type in a different password as password confirmation
Then I see an error telling me my passwords don't match.

**Comment by iandouglas** [comment]
@mikedao if we move to password-less auth, we can drop the password/bcrypt stuff completely. How do you want to proceed here? Users will still need to register, but won't need to give us a password at all.

**Comment by rolentle** [comment]
@iandouglas @mikedao just saw this note 🤦
