### ISSUE TITLE
user can toggle active state for a character for a campaign, which disables all others on that campaign

### ISSUE THREAD

**Issue by iandouglas** [mikedao/cobalt_reserve#57]
As a user:
if I have no active characters for the current campaign, the next character I create should be made immediately active
if I have an active character for the current campaign, the next character I create should not be made active
if there's no active campaign, I should not be able to create a new character

if I toggle a character to be active, all other characters should be made inactive

**Comment by mikedao** [comment]
Can we also add in a method for a user that will return its active character?

**Comment by iandouglas** [comment]
sounds like a new feature request :)
