### ISSUE TITLE
Level validation occasionally makes tests fail.

### ISSUE THREAD

**Issue by mikedao** [mikedao/cobalt_reserve#71]
**Describe the bug**
Intermittently, `character_edit_spec:91`and `user_can_see_characters_spec:19` fail level validation of level being greater than 1. 

**To Reproduce**
1. Pulled main.
2. Yolo'ed database
3. Ran tests, saw one failure. Ran tests, saw two failures. Ran tests, no failures.

**Expected behavior**
Tests all pass, every time.

**Comment by mikedao** [comment]
Unique name validation also failed once.

**Comment by iandouglas** [comment]
Super annoying. Shoulda Matchers wouldn't play nicely for some reason so I had to hand roll some testing, and I think that using FactoryBotb might be part of the issue.

**Comment by mikedao** [comment]
Would the simplest thing to do be to strip FactoryBot out? Not really the END of the world
